### ISSUE TITLE
截图中vim的sign与nerdtree的左侧线是怎么做到的?

### ISSUE THREAD

**Issue by haolian9** [ashfinal/vimrc-config#1]
嗨, 我发现你的这份配置中的截图 ![screen-shot](https://github.com/ashfinal/vimrc-config/blob/master/screenshots/screenshot-mac.png)的两个效果很不错!
- nerdtree 的左侧显示了一条红色的线
- vim右侧窗口的sign显示了fold的层级

请问, 你是怎么做到的？

**Comment by ashfinal** [comment]
1. 这不是 nerdtree，是vim内置的文件浏览器 netrw。会显示文件层级（如下图），功能齐全够用。
2. set foldcolumn＝1 反正大于0就行。这个在配置中默认没开，你可以使用`<leader>` + `m` 来切换显示。

<img width="214" alt="screen shot 2016-06-08 at 8 14 37 pm" src="https://cloud.githubusercontent.com/assets/6827900/15893975/b68d3f20-2db5-11e6-8098-3af898989d90.png">

**Comment by haolian9** [comment]
get! 谢谢
